name: sfdify_scm
description: "SFDIFY SCM - Clean Architecture Flutter App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_hooks: ^0.21.2
  flutter_svg: ^2.0.17
  fpdart: ^1.1.1
  freezed_annotation: ^3.0.0
  gap: ^3.0.1
  get_it: ^9.2.0
  go_router: ^17.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hydrated_bloc: ^10.0.0
  injectable: ^2.5.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.5.0
  replay_bloc: ^0.3.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: ^3.0.4
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.4
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
